version: '3.4'

services:
  mongo-db:
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - '27017:27017'
  server:
    build: .
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    links:
      - mongo-db
    container_name: portfolio-server
  client:
    build: client
    volumes:
      - ./client:/usr/src/app
    ports:
      - 4200:4200
    container_name: portfolio-client

