version: '3.4'

services:
  mongo-db:
    image: mongo
    ports:
      - '27017:27017'
  server:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    links:
      - mongo-db
  client:
    build: client
    volumes:
      - ./client:/usr/src/app
    ports:
      - 4200:4200

