version: '3.4'

services:
  server:
    build: .
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    container_name: ecommerce-server
  client:
    build: client
    volumes:
      - ./client:/usr/src/app
    ports:
      - 4200:4200
    container_name: ecommerce-client

